FROM registry.fedoraproject.org/fedora:43

RUN dnf5 -y install \
      openssh-clients \
      podman \
      procps-ng \
      qemu-img \
      qemu-system-x86-core \
      edk2-ovmf \
    && dnf5 clean all

COPY run-tests.sh /usr/local/bin/run-tests.sh
RUN chmod 0755 /usr/local/bin/run-tests.sh

ENTRYPOINT ["/usr/local/bin/run-tests.sh"]
