# that os should not be installed from a standalone iso
# following disk image is only for testing usage and contains settings not intended for final os image 

[[customizations.filesystem]]
mountpoint = "/"
minsize = "20 GiB"

[[customizations.files]]
path = "/etc/ssh/sshd_config.d/99-test.conf"
data = """
ListenAddress 0.0.0.0:22
"""

[[customizations.firewall.services]]
enabled = ["sshd"]

[[customizations.firewall]]
ports = ["22"]

[[customizations.user]]
name = "test_user"
password = "test"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKeSG5gIy8/M1tjJ0b1kXlNiLrD/Me+qGUdlnouRvOO3"
groups = ["wheel"]